---
title: "SDS 192: Mini-Project 3"
author: Olivia DeMeo and Lilly Farah
date: 4/16/19
output:
  html_document:
    code_folding: hide

---

```{r message = FALSE, echo = TRUE}

library(sf)
library(tidyverse)
library(leaflet)
library(macleish)


```

##Problem:
### "MacLeish has approximately four miles of built trail for use by field station visitors. We would like to be able to classify these trails as “Easy,” “Moderate,” or “Difficult” based on their length and change in elevation."

```{r, message = FALSE, echo = TRUE}

macleish_layers %>%
  pluck("trails") %>%
  st_length()

trail_lengths <- macleish_layers %>%
  pluck("trails") %>%
  mutate(computed_length = st_length(geometry))

x <- st_intersection(
  pluck(macleish_layers, "trails"), 
  pluck(macleish_layers, "contours_30ft")
)
western <- filter(x, name == "Western Loop")
western_pts <- western %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")


porc <- filter(x, name == "Porcupine Trail")
porc_pts <- porc %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

poplar <- filter(x, name == "Poplar Hill Road")
poplar_pts <- poplar %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

eastern <- filter(x, name == "Eastern Loop")
eastern_pts <- eastern %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

vernal <- filter(x, name == "Vernal Pool Loop")
vernal_pts <- vernal %>% 
  st_cast("MULTIPOINT") %>% 
  st_cast("POINT")

leaflet() %>%
  addTiles() %>%
  addPolylines(data = pluck(macleish_layers, "trails"), color = "red") %>%
  addPolygons(data = macleish_layers[["boundary"]], color = "black", fillOpacity = 0) %>%
  addPolylines(data = macleish_layers[["contours_30ft"]], color = "blue", weight = 0.75) %>%
  addMarkers(data = western_pts) %>%
  addMarkers(data = porc_pts)%>%
  addMarkers(data = poplar_pts)%>%
  addMarkers(data = eastern_pts)%>%
  addMarkers(data = vernal_pts)

```

